This notebook verifies that the Bogard ESM dataset I used for geocoding can be joined to the original BogardMapLakes data on GEE. Furthermore, it counts how many of the lakes that were geocoded originally couldn't be matched to PLD (answer: 15).

In [ ]:
import geopandas as gpd
import pandas as pd
import numpy as np

# from land_cover.geocode import out_gdb_pth as geocode_pth
from land_cover.load import loadBogardSuppl
from land_cover.load import gee_table_pth

In [2]:
version = "v3"
_, out_dir, file_name = loadBogardSuppl()
out_spatial_stem = out_dir / "shp" / "qa_qc" / f"{file_name}_geocoded_{version}"
geocode_pth = f"{out_spatial_stem}.gpkg"
updated_gee_pth = "/Volumes/metis/ABOVE3/Tom/gee_input/updated/gee_cleaned_geocode_2025-07-10.csv"
print(geocode_pth)

/Volumes/metis/ABOVE3/Bogard_suppl_data/edk_out/shp/qa_qc/Bogard19_ESM_alldata_wh_geocoded_v3.gpkg

In [3]:
# Load gee table as DataFrame and convert to GeoDataFrame
gee_df = pd.read_csv(gee_table_pth)
gee_gdf = gpd.GeoDataFrame(
    gee_df,
    geometry=gpd.points_from_xy(gee_df['Longitude'], gee_df['Latitude']),
    crs="EPSG:4326"
)

# Load geocode table as GeoDataFrame
geocode_gdf = gpd.read_file(geocode_pth)
len(gee_gdf)

8714

In [4]:
geocode_gdf.columns

Index(['Category (1=same as YFB lakes/2=different)', 'coscatsID', 'Sbcode',
       'otherID provided', 'lake name provided', 'lat (decimal)',
       'long (decimal)', 'pco2 (uatm)', 'replicates (number)',
       'CO2 analysis method', 'Original reference',
       'Current reference (if applicable)', 'additional notes ',
       'geocode_full_name', 'geocode_lat', 'geocode_lon', 'geocode_id',
       'geocode_item_class', 'geocode_item_type', 'geocode_geom', 'geocoder',
       'QA', 'geometry'],
      dtype='object')

In [5]:
# First, set QA pass columns to not geocoded
geocode_fail_idx = geocode_gdf.query("QA == 0").index
geocode_gdf.loc[geocode_fail_idx, ["geocoder", "geocode_full_name", "geocode_lat", "geocode_lon"]] = (
    np.nan
)
geocode_gdf.loc[geocode_fail_idx, ["geocode_geom"]] = False

In [6]:
# How many matched features had no lat/lon? Actually, all have lat/lon
count_bogard_suppl_with_coords = geocode_gdf[
    geocode_gdf["lat (decimal)"].notnull() & geocode_gdf["long (decimal)"].notnull()
].shape[0]

count_geocode_no_coords = geocode_gdf[(geocode_gdf['geocoder'].notnull()) & (geocode_gdf['lat (decimal)'].isnull())].shape[0]
print(
    f"Number of bogard_suppl features with lat/lon: {count_bogard_suppl_with_coords} / {len(geocode_gdf)}"
)
print(
    f"Number of geocoded features with no lat/lon: {count_geocode_no_coords} / {len(geocode_gdf)}"
)

Number of bogard_suppl features with lat/lon: 922 / 922
Number of geocoded features with no lat/lon: 0 / 922

In [7]:
gee_bogard_wh = gee_gdf.query("WesternHem == True and Source == 'BogardMapLakes'")
print(f"Original length of Bogard gee_gdf in WH: {len(gee_bogard_wh)}")
print(f"Original length of Bogard SI data: {len(geocode_gdf)}")

Original length of Bogard gee_gdf in WH: 680
Original length of Bogard SI data: 922

All in shapefile/GEE are unique. Many in SI are not- probably why they were removed from shapefile.

In [8]:
# number from gee without duplicate lat/lon (none) ✅
np.unique(gee_bogard_wh[["Latitude", "Longitude"]], axis=0).shape[0]

680

In [9]:
# number from SI without duplicate lat/lon (none) ✅
np.unique(geocode_gdf[["lat (decimal)", "long (decimal)"]], axis=0).shape[0]

676

In [10]:
# Perform inner join based on Latitude/Longitude (gee) and lat (decimal)/long (decimal) (geocode)
merged_gdf = gee_bogard_wh.merge(
    geocode_gdf,
    how="inner",
    left_on=["Latitude", "Longitude"],
    right_on=["lat (decimal)", "long (decimal)"],
    suffixes=("_gee", "_geocode"),
)
print(f"Length of merged_gdf (inner join): {len(merged_gdf)}")

Length of merged_gdf (inner join): 539

In [11]:
merged_gdf

,system:index,CurrentlyM,Latitude,Longitude,SampleUID,Source,WesternHem,.geo,geometry_gee,Category (1=same as YFB lakes/2=different),...,geocode_full_name,geocode_lat,geocode_lon,geocode_id,geocode_item_class,geocode_item_type,geocode_geom,geocoder,QA,geometry_geocode
0,0000000000000000039a,0,47.88571,-71.250890,BML_00000031,BogardMapLakes,True,"{""type"":""Point"",""coordinates"":[-71.25089217145...",POINT (-71.25089 47.88571),2.0,...,"Lac Talbot, Lac-Pikauba, Charlevoix, Capitale-...",47.862632,-71.253433,1449957,natural,water,True,nominatim,NaN,"POLYGON ((-71.26443 47.88455, -71.26423 47.884..."
1,000000000000000003b7,0,48.12674,-71.286690,BML_00000060,BogardMapLakes,True,"{""type"":""Point"",""coordinates"":[-71.28668983471...",POINT (-71.28669 48.12674),2.0,...,"Lac Laurier, Lac-Ministuk, Le Fjord-du-Saguena...",48.127904,-71.286518,111417577,natural,water,True,nominatim,NaN,"POLYGON ((-71.29011 48.12669, -71.29009 48.126..."
2,000000000000000003b7,0,48.12674,-71.286690,BML_00000060,BogardMapLakes,True,"{""type"":""Point"",""coordinates"":[-71.28668983471...",POINT (-71.28669 48.12674),2.0,...,"Lac Laurier, Lac-Ministuk, Le Fjord-du-Saguena...",48.127904,-71.286518,111417577,natural,water,True,nominatim,NaN,"POLYGON ((-71.29011 48.12669, -71.29009 48.126..."
3,000000000000000003b8,0,48.12675,-71.286850,BML_00000061,BogardMapLakes,True,"{""type"":""Point"",""coordinates"":[-71.28685036235...",POINT (-71.28685 48.12675),2.0,...,"Lac Laurier, Lac-Ministuk, Le Fjord-du-Saguena...",48.127904,-71.286518,111417577,natural,water,True,nominatim,NaN,"POLYGON ((-71.29011 48.12669, -71.29009 48.126..."
4,000000000000000003bc,0,48.12947,-71.258607,BML_00000065,BogardMapLakes,True,"{""type"":""Point"",""coordinates"":[-71.25860641627...",POINT (-71.25861 48.12947),2.0,...,"Lac du Quai, Lac-Ministuk, Le Fjord-du-Saguena...",48.129056,-71.259032,111416276,natural,water,True,nominatim,NaN,"POLYGON ((-71.25987 48.12914, -71.25983 48.128..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,00000000000000001b59,1,70.45475,-156.947900,BML_00006110,BogardMapLakes,True,"{""type"":""Point"",""coordinates"":[-156.9478983529...",POINT (-156.9479 70.45475),2.0,...,None,NaN,NaN,None,None,None,False,None,NaN,None
535,00000000000000001b5c,1,70.72825,-156.842900,BML_00006113,BogardMapLakes,True,"{""type"":""Point"",""coordinates"":[-156.8428999004...",POINT (-156.8429 70.72825),2.0,...,None,NaN,NaN,None,None,None,False,None,NaN,None
536,00000000000000001b5f,1,71.19909,-156.665360,BML_00006116,BogardMapLakes,True,"{""type"":""Point"",""coordinates"":[-156.6653607920...",POINT (-156.66536 71.19909),2.0,...,None,NaN,NaN,None,None,None,False,None,NaN,None
537,00000000000000001b60,1,71.24163,-156.773910,BML_00006117,BogardMapLakes,True,"{""type"":""Point"",""coordinates"":[-156.7739086889...",POINT (-156.77391 71.24163),2.0,...,None,NaN,NaN,None,None,None,False,None,NaN,None
538,00000000000000001b61,1,71.27396,-156.497000,BML_00006118,BogardMapLakes,True,"{""type"":""Point"",""coordinates"":[-156.4969985135...",POINT (-156.497 71.27396),2.0,...,None,NaN,NaN,None,None,None,False,None,NaN,None

In [12]:
# How many features (from inner join) were geocoded?
matched = merged_gdf[merged_gdf['geocode_full_name'].notnull()]
matched_count = len(matched)
matched_left_count = matched[matched['SampleUID'].notnull()].shape[0]
print(f"Number of geocoded features: {matched_count} / {merged_gdf.shape[0]} common")
# print(f"Number of matched features in og Bogard_lakes shp: {matched_count} / {matched_left_count}")
print(
    f"Number of geocoded features with PLD: {len(matched[matched.CurrentlyM == 1])} / {matched_count}"
)

Number of geocoded features: 178 / 539 common
Number of geocoded features with PLD: 163 / 178

# Save gee with updated matching column and secondary lat/lon

In [14]:
# Perform inner join on full gee dataset- dropping duplicates in right df ensures
# same number of rows as OG left df
merged_left_gdf = gee_gdf.merge(
    geocode_gdf.drop_duplicates(subset=["lat (decimal)", "long (decimal)"]),
    how="left",
    left_on=["Latitude", "Longitude"],
    right_on=["lat (decimal)", "long (decimal)"],
    suffixes=("_gee", "_geocode"),
    # validate="one_to_one",
)
len(merged_left_gdf)

8714

In [15]:
# updated match column if it was already 0
merged_left_gdf.loc[
    (merged_left_gdf.CurrentlyM == 0) & (merged_left_gdf.geocoder.notnull()), "CurrentlyM"
] = 2

In [27]:
merged_left_gdf.rename({"lake name provided": "lk_name_provided"}, axis=1, inplace=True)
# add geometry field, but save as csv
merged_left_gdf["geometry"] = gpd.points_from_xy(
    merged_left_gdf["Longitude"], merged_left_gdf["Latitude"]
)
og_columns = list(gee_df.columns)
columns_to_keep = og_columns[1:7] + [
    "lk_name_provided",
    "geocode_full_name",
    "geocode_lat",
    "geocode_lon",
    "geocode_geom",
    "geometry",
]

In [28]:
merged_left_gdf[columns_to_keep]

,CurrentlyM,Latitude,Longitude,SampleUID,Source,WesternHem,lk_name_provided,geocode_full_name,geocode_lat,geocode_lon,geocode_geom,geometry
0,0,51.381753,179.230050,EFL_00000026,EffluxLakes,False,NaN,NaN,NaN,NaN,NaN,POINT (179.23005 51.38175)
1,0,51.367310,179.275885,EFL_00000027,EffluxLakes,False,NaN,NaN,NaN,NaN,NaN,POINT (179.27588 51.36731)
2,0,51.401477,179.266438,EFL_00000028,EffluxLakes,False,NaN,NaN,NaN,NaN,NaN,POINT (179.26644 51.40148)
3,0,51.603712,178.816393,EFL_00000029,EffluxLakes,False,NaN,NaN,NaN,NaN,NaN,POINT (178.81639 51.60371)
4,0,51.392038,179.391441,EFL_00000033,EffluxLakes,False,NaN,NaN,NaN,NaN,NaN,POINT (179.39144 51.39204)
...,...,...,...,...,...,...,...,...,...,...,...,...
8709,1,63.709000,-112.573333,LRL_00001566,LitReviewLakes,True,NaN,NaN,NaN,NaN,NaN,POINT (-112.57333 63.709)
8710,1,64.100167,-113.025667,LRL_00001568,LitReviewLakes,True,NaN,NaN,NaN,NaN,NaN,POINT (-113.02567 64.10017)
8711,1,63.690333,-113.444667,LRL_00001569,LitReviewLakes,True,NaN,NaN,NaN,NaN,NaN,POINT (-113.44467 63.69033)
8712,1,63.336833,-113.705000,LRL_00001570,LitReviewLakes,True,NaN,NaN,NaN,NaN,NaN,POINT (-113.705 63.33683)
8713,1,68.433455,-159.174802,LRL_00001574,LitReviewLakes,True,NaN,NaN,NaN,NaN,NaN,POINT (-159.1748 68.43345)

In [29]:
merged_left_gdf[columns_to_keep].to_csv(updated_gee_pth, index=False)

In [26]:
# Save merged_left_gdf with geometry as WKT in a CSV
merged_left_gdf_with_wkt = merged_left_gdf.copy()
merged_left_gdf_with_wkt['geometry_wkt'] = merged_left_gdf_with_wkt.geometry.apply(lambda geom: geom.wkt if geom is not None else None)
# merged_left_gdf_with_wkt[columns_to_keep + ['geometry_wkt']].to_csv(
#     out_dir / "gee_cleaned_geocode_with_geom.csv", index=False
# )
merged_left_gdf_with_wkt

AttributeError: You are calling a geospatial method on the GeoDataFrame, but the active geometry column ('geometry') is not present.
There are columns with geometry data type (['geometry_gee', 'geometry_geocode']), and you can either set one as the active geometry with df.set_geometry("name") or access the column as a GeoSeries (df["name"]) and call the method directly on it.

# Now, figure out which lakes from SI are new

In [12]:
# Perform right join based on Latitude/Longitude (gee) and lat (decimal)/long (decimal) (geocode)
merged_right_gdf = gee_bogard_wh.merge(
    geocode_gdf,
    how="right",
    left_on=["Latitude", "Longitude"],
    right_on=["lat (decimal)", "long (decimal)"],
    suffixes=("_gee", "_geocode"),
)
null_sampleuid_mask = merged_right_gdf["SampleUID"].isnull()
num_null_sampleuid = null_sampleuid_mask.sum()
print(
    f"Number of rows in merged_right_gdf with null SampleUID: {num_null_sampleuid} / {len(merged_right_gdf)}"
)

Number of rows in merged_right_gdf with null SampleUID: 383 / 922

In [15]:
additional_si_lakes = geocode_gdf[null_sampleuid_mask]

In [21]:
# How many additional lakes from SI were not geocoded?
additional_si_lakes.geocoder.isnull().sum()

np.int64(383)

In [22]:
additional_si_lakes

,Category (1=same as YFB lakes/2=different),coscatsID,Sbcode,otherID provided,lake name provided,lat (decimal),long (decimal),pco2 (uatm),replicates (number),CO2 analysis method,...,additional notes,geocode_full_name,geocode_lat,geocode_lon,geocode_id,geocode_item_class,geocode_item_type,geocode_geom,geocoder,geometry
0,1.0,9.0,823.0,Meta Analysis lakes from Sobek et al 2005 Glob...,None,76.509,-86.797,550.00,1.0,pH&IC,...,None,None,NaN,NaN,None,None,None,False,None,None
1,1.0,9.0,823.0,Meta Analysis lakes from Sobek et al 2005 Glob...,R,76.555,-86.582,498.00,1.0,pH&IC,...,None,None,NaN,NaN,None,None,None,False,None,None
88,1.0,NaN,NaN,None,JR03,70.550,-95.020,275.53,NaN,"calc. from ph, temperature, DIC",...,None,None,NaN,NaN,None,None,None,False,None,None
241,2.0,NaN,NaN,None,JR01,69.150,-95.120,901.47,NaN,"calc. from ph, temperature, DIC",...,None,None,NaN,NaN,None,None,None,False,None,None
242,2.0,NaN,NaN,None,JR04,70.450,-95.030,194.40,NaN,"calc. from ph, temperature, DIC",...,None,None,NaN,NaN,None,None,None,False,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,NaN,50.0,816.0,Meta Analysis lakes from Sobek et al 2005 Glob...,V,78.933,-104.541,816.00,1.0,pH&IC,...,None,None,NaN,NaN,None,None,None,False,None,None
880,NaN,50.0,816.0,Meta Analysis lakes from Sobek et al 2005 Glob...,LAH,78.813,-103.667,649.00,1.0,pH&IC,...,None,None,NaN,NaN,None,None,None,False,None,None
881,NaN,105.0,823.0,Meta Analysis lakes from Sobek et al 2005 Glob...,None,68.434,-66.844,135.00,1.0,pH&IC,...,None,None,NaN,NaN,None,None,None,False,None,None
882,NaN,105.0,823.0,Meta Analysis lakes from Sobek et al 2005 Glob...,None,68.432,-66.841,256.00,1.0,pH&IC,...,None,None,NaN,NaN,None,None,None,False,None,None
883,NaN,50.0,816.0,Meta Analysis lakes from Sobek et al 2005 Glob...,None,78.817,-103.667,462.00,1.0,pH&IC,...,None,None,NaN,NaN,None,None,None,False,None,None